spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8889/sr03
    username: root
    password: aptx4969
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #      更新或者创建数据表结构
      ddl-auto: update
    #      控制台显示sql
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/

  mvc:
    date-format: yyyy-MM-dd
server:
  context-path: /demo

