spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8889/sr03
    username: root
    password: aptx4969
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
server:
  context-path: /demo


